- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars_file:
    - vars.yml

  tasks:

   - name: Launch instances
     gce:
         instance_names: informatics
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         pem_file: "{{ pem_file }}"
         project_id: "{{ project_id }}"
