---
- hosts: local
  connection: local
  gather_facts: False
  tasks:
      - name: Start Droplet
        digital_ocean: >
            state=present
            command=droplet
            size_id=62
            region_id=1
            image_id=10581649
            ssh_key_ids=14937
            name=minecraft
            unique_name=yes
            wait_timeout=500
        register: informatics 
      - name: Add to hosts list
        add_host: hostname={{ informatics.droplet.ip_address }} groupname=informatics


